### ISSUE TITLE
.hex Files

### ISSUE THREAD

**Issue by ghost** [mbuettner/hexagony#3]
On the FizzBuzz examples, the extension is `.hex`, which is a [file encoded in hexadecimal](http://file.org/extension/hex). I reckon that the `.hxg` file extension, which is unique to Hexagony (almost), is better. Also, the other files have the extension `.hxg`, so why not that one as well?

**Comment by m-ender** [comment]
Oh, you're right. That was from an old version of the Esoteric IDE. I had
already fixed it but forgot to commit it. Will push those files later.
