### ISSUE TITLE
Random Functionality Missing

### ISSUE THREAD

**Issue by sunnypp** [mbuettner/hexagony#6]
Currently Hexagony has exhausted all symbols on a usual keyboard as operators.
However, there is no way to generate randomness.

(Here "Random number" means an integer between 0...5.  Just as an example of randomness)
Suggestions:
- Use `Tab` instead for debug flag and thus freeing ` for generating random numbers.  As Debug flag is usually not shown on shared code, the harm on layout will only affect the developer.  Or, the debug flag is replaced by special chars.
- Using `;` to print control characters gives extra functionalities.  This is inconsistent with the other operators which operates on its own (1 byte).  This option gives more room for additional features in Hexagony.

**Comment by m-ender** [comment]
Originally, I was planning use `$` as a random operator, but Timwi (https://github.com/Timwi) suggested turning it into a jump, and I have to say I'm quite happy with that decision in hindsight.

I'll think about using ```, but I'm not sure I'd like to change the spec of Hexagony at all at this point.

That said, I considered implementing five different kinds of randomness, either depending on the direction the IP is moving in or on which IP you're currently using. Several ideas were random IP, random direction, random memory movement, random value, etc.

**Comment by 12Me21** [comment]
Perhaps you could make division or modulo by 0 set the current memory edge to a random number between 0 and the other value. Currently it just throws an error which ends the program, so I don't think it would affect current programs.

**Comment by m-ender** [comment]
Actually, quite a lot of golfed programs make use of that, to terminate the
program conditionally.

**Comment by m-lohmann** [comment]
Why would you want to get rid of implementing your own [linear congruential generator](https://rosettacode.org/wiki/Linear_congruential_generator)? Where would be the fun in that? If you need simple pseudorandom numbers without any higher requirements a simple LCG should suffice, and it’s not too hard to implement.
