### ISSUE TITLE
STDIN documentation clarity

### ISSUE THREAD

**Issue by sparr** [mbuettner/hexagony#7]
> `?` reads and discards from STDIN until a digit, a - or a + is found. Then reads as many characters as possible to form a valid (signed) decimal integer and sets the current memory edge to its value. Returns 0 once EOF is reached.

From the README alone, it is unclear to me whether or not the character immediately after the end of the number is discarded or left for the next `,` to consume.

**Comment by m-ender** [comment]
The next character is not consumed. I'll try to remember to clarify the README.

**Comment by m-ender** [comment]
Of course I didn't remember. Fixed now.
